$ESXiServer = "172.30.0.10"
$ESXiRootPassowrd = "VMware1!"

$VCFInstallerVMName = "sddcm01"
$VCFInstallerFQDN = "sddcm01.vcf.lab"
$VCFInstallerRootPassword = "VMware1!VMware1!"

$SSHKeys = ""

# See https://williamlam.com/2026/05/vcf-9-1-comprehensive-vcf-installer-sddc-manager-configuration-workarounds-for-lab-deployments.html for list of configuration overrides

# Configuration overrides to be added to /home/vcf/feature.properties
$VCFFeatureProperties = @{
    "feature.vcf.vgl-29121.single.host.domain" = "true"
    "feature.vcf.vgl-43370.vsan.esa.sddc.managed.disk.claim" = "true"
}

# Configuration overrides to be added to /etc/vmware/vcf/domainmanager/application.properties
$VCFDomainManagerProperties = @{
    "vsan.esa.sddc.managed.disk.claim" = "true"
}

# Configuration overrides to be added to /etc/vmware/vcf/operationsmanager/application-prod.properties
$VCFOperationsManagerProperties = @{
    "vsan.esa.sddc.managed.disk.claim" = "true"
}

$VCFInstallerOfflineDepot = "http://172.30.50.29:8888"

#### DO NOT EDIT BEYOND HERE ####


Function My-Logger {
    param(
        [Parameter(Mandatory=$true)][String]$message,
        [Parameter(Mandatory=$false)][String]$color="green"
    )


    $timeStamp = Get-Date -Format "MM-dd-yyyy_hh:mm:ss"


    Write-Host -NoNewline -ForegroundColor White "[$timestamp]"
    Write-Host -ForegroundColor $color " $message"
}

My-Logger "Waiting for VCF Installer UI to be ready ..."
while(1) {
    try {
        $requests = Invoke-WebRequest -Uri "https://${VCFInstallerFQDN}/vcf-installer-ui/login" -Method GET -SkipCertificateCheck -TimeoutSec 5
        if($requests.StatusCode -eq 200) {
            My-Logger "`tVCF Installer UI https://${VCFInstallerFQDN}/vcf-installer-ui/login is now ready!"
            break
        }
    }
    catch {
        My-Logger "VCF Installer UI is not ready yet, sleeping for 120 seconds ..."
        sleep 120
    }
}

$payload = @{
    "username" = "admin@local"
    "password" = $VCFInstallerRootPassword
}

$body = $payload | ConvertTo-Json

$headers = @{
    "Content-Type" = "application/json"
}
My-Logger "Retrieving access token from VCF Installer ..."
$request = Invoke-WebRequest -Uri https://${VCFInstallerFQDN}/v1/tokens -Method POST -Body $body -Headers $headers -SkipCertificateCheck
if($request.StatusCode -eq 200) {
    $accesToken = ($request.Content | ConvertFrom-Json).accessToken
}

$headers += @{
    "Authorization" = "Bearer ${accesToken}"
}

$depotPayload = @{
    "depotConfiguration" = @{
        "isOfflineDepot" = $true
        "url" = $VCFInstallerOfflineDepot
    }
}
$depotBody = $depotPayload | ConvertTo-Json

My-Logger "Configuring HTTP Offline Depot for VCF Installer ..."
$request = Invoke-WebRequest -Uri https://${VCFInstallerFQDN}/v1/system/settings/depot -Method PUT -Body $depotBody -Headers $headers -SkipCertificateCheck

My-Logger "Connecting to ESXi Host $VIServer ..."
$viConnection = Connect-VIServer $ESXiServer -User root -Password $ESXiRootPassowrd -WarningAction SilentlyContinue

$vcfVM = Get-VM -Server $viConnection $VCFInstallerVMName


$scriptName = "vcfIntScript.sh"
$script = @"
#!/bin/bash
# Generated by William Lam's VCF 9.1 Lab in a Box Script

"@


if($SSHKeys -ne "") {
    $script += "echo `"${SSHKeys}`" > /root/.ssh/authorized_keys`n"
    $script += "sed -i 's/^PermitRootLogin.*/PermitRootLogin yes/g' /etc/ssh/sshd_config`n"
    $script += "systemctl restart sshd`n"
}

$vcfDomainConfigFile = "/etc/vmware/vcf/domainmanager/application.properties"
if($VCFDomainManagerProperties -ne $null) {
    $VCFDomainManagerProperties.GetEnumerator() | Foreach-Object {
        $script += "echo $($_.key)=$($_.value) >> ${vcfDomainConfigFile}`n"
    }
}

$vcfOperationsConfigFile = "/etc/vmware/vcf/operationsmanager/application-prod.properties"
if($VCFOperationsManagerProperties -ne $null) {
    $VCFOperationsManagerProperties.GetEnumerator() | Foreach-Object {
        $script += "echo $($_.key)=$($_.value) >> ${vcfDomainConfigFile}`n"
    }
}

$vcfFeatureConfigFile = "/home/vcf/feature.properties"
$VCFFeatureProperties.GetEnumerator() | Foreach-Object {
    $script += "echo $($_.key)=$($_.value) >> ${vcfFeatureConfigFile}`n"
}
$script += "chmod 755 ${vcfFeatureConfigFile}`n"

$script += "echo 'y' | /opt/vmware/vcf/operationsmanager/scripts/cli/sddcmanager_restart_services.sh"

$script | Out-File $scriptName

My-Logger "Transferring configuration shell script ($scriptName) to VCF Installer VM ..."
Copy-VMGuestFile -Server $viConnection -VM $vcfVM -GuestUser "root" -GuestPassword $VCFInstallerRootPassword -LocalToGuest -Source ${scriptName} -Destination /tmp/${scriptName} -Force | Out-Null


My-Logger "Running configuration shell script on VCF Installer VM ..."
Invoke-VMScript -ScriptText "bash /tmp/${scriptName}" -VM $vcfVM -GuestUser "root" -GuestPassword $VCFInstallerRootPassword  | Out-Null


My-Logger "Disconnecting from ESXi Host $VIServer ..."
Disconnect-VIServer $viConnection -Confirm:$false
